DDCNL-3943 | play2.8 upgrade
hmrc/govuk-template pull request #113
Opened 2021-04-29 15:07 UTC by shikkhasingh

2021-04-29 16:03 UTC, struong commented
This failed to compile btw, check the PR builder

2021-04-29 16:03 UTC, struong requested changes

2021-04-29 16:03 UTC, struong commented on project/plugins.sbt
> +    case "2.8" => "com.typesafe.play" % "sbt-plugin" % "2.8.0"
Lets take on 2.8.7

2021-05-04 13:01 UTC, struong approved these changes, later dismissed

2021-05-27 16:05 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2021-05-27 16:05 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2021-05-27 16:05 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2021-05-27 16:05 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2021-05-28 12:26 UTC, vimalsuresh approved these changes

2021-06-02 10:12 UTC, merged