Added a Google analytics custom dimension for tai CY+1 estimated income
hmrc/govuk-template pull request #56
Opened 2019-01-16 15:24 UTC by oc-ste

2019-01-16 16:13 UTC, RaminEsfandiari approved these changes

2019-02-25 14:28 UTC, daniel-manning commented on resources/templates/mustache/preprod/govuk-template.mustache.html
> -            {{#gaCustomEvent}}
Did you mean to remove this?

2019-02-25 14:30 UTC, oc-ste commented on resources/templates/mustache/preprod/govuk-template.mustache.html
> -            {{#gaCustomEvent}}
No, it's just a new line

2019-02-25 14:37 UTC, daniel-manning requested changes

2019-02-25 14:37 UTC, daniel-manning commented on resources/templates/mustache/preprod/govuk-template.mustache.html
> -            {{#gaCustomEvent}}
you'll need to add it back

2019-02-26 14:38 UTC, daniel-manning approved these changes

2019-02-26 14:57 UTC, merged