Add language switching support & welsh content
hmrc/govuk-template pull request #68
Opened 2019-08-16 14:19 UTC by palequezal

2019-09-05 15:33 UTC, danewatts requested changes

2019-09-05 15:33 UTC, danewatts commented on src/main/play-25/twirl/views/layouts/govuk_template.scala.html
> +        <title>@title.getOrElse(Messages("base.title.default"))</title>
You have brought implicit messages in however use the Messages object. Please switch this for all messages.

2019-09-05 15:33 UTC, danewatts commented on resources/messages.cy
> +base.skip_link                                  = Ewch yn syth i''r prif gynnwys
Replace alll dumb quotes with smart quotes please

2019-09-05 15:33 UTC, danewatts commented on project/LibDependencies.scala
> +    "org.jsoup" % "jsoup" % "1.8.1" % Test
There is more recent compatible versions of the 2 additional libraries added. Can you update them please?

2019-09-06 09:05 UTC, Jackie1988 commented
Hi there, I am a dev on Live Services DDCW, we are currently implementing welsh translation on one of our services, we have noticed there is still some english content in the footer - that this PR fixes - that the welsh translation unit could fail us on, does anyone know when this will be merged? Many thanks

2019-09-06 09:06 UTC, danewatts commented
@Jackie1988 hey, I have requested changes to this PR. Please address these changes.

2019-09-06 13:19 UTC, danewatts approved these changes

2019-09-06 13:20 UTC, merged

2019-09-06 13:22 UTC, Jackie1988 commented
Hi @palequezal when will this PR be reviewed and updated? Thanks

2019-09-06 13:22 UTC, danewatts commented
@Jackie1988 it is already merged?

2019-09-06 13:31 UTC, Jxr227 commented
#6 Is this fixed as part of this PR?

2019-09-06 14:33 UTC, Jxr227 commented
@danewatts Looks like the build failed because it's using oraclejdk8 which looks like it could be this: https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038

2019-09-06 14:58 UTC, danewatts commented
I have reverted this due to a failing build. This is due to cross-compilation for play versions. I am happy to merge this back in once it is tested for both play versions. Please see: https://github.com/hmrc/sbt-play-cross-compilation for reference.