DEP-22 put JavaScript for nuance in prod
hmrc/govuk-template pull request #81
Opened 2019-12-09 09:26 UTC by tonymyers

2019-12-10 16:37 UTC, kurtlogan commented on resources/templates/mustache/production/govuk-template.mustache.html
> +           {{#nuanceWebChat}}
Why does this need wrapped in a `nuanceWebChat` and `isWebchatEnabled`

2019-12-10 16:44 UTC, kurtlogan approved these changes

2019-12-10 16:44 UTC, kurtlogan requested changes

2019-12-10 16:44 UTC, kurtlogan commented on resources/templates/mustache/production/govuk-template.mustache.html
> +                                'sessionId': '{{{nuanceId}}}'
This doesn't need triple braces

2019-12-11 08:17 UTC, tonymyers commented on resources/templates/mustache/production/govuk-template.mustache.html
> +                                'sessionId': '{{{nuanceId}}}'
Removed the extra brackets, thanks.

2019-12-11 09:08 UTC, closed without merging